#

services:
  Api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI-API-KEY=${OPENAI_API_KEY}
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8100:8000"
    volumes:
      - chroma_data:/chroma/chroma

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    enviroment:
      -
      -
      -
    volumes:
      -
    
    
    volumes:
      chroma_data:
      pg_data: